blank_issues_enabled: true
contact_links:
  - name: â“ Ask a question
    url: https://github.com/openmeterio/openmeter/discussions/new?category=q-a
    about: Ask and discuss questions with other OpenMeter community members

  - name: ğŸ’¬ Discord
    url: https://discord.gg/nYH3ZQ3Xzq
    about: Please ask and answer questions here
