emit:
  - '@typespec/openapi3'
parameters:
  base-dir:
    default: '{cwd}'
output-dir: '{base-dir}'
options:
  '@typespec/openapi3':
    emitter-output-dir: '{output-dir}/output'
linter:
  extends:
    - '@openmeter/api-spec/all'
