emit:
  - '@typespec/http-client-python'
parameters:
  base-dir:
    default: '{cwd}'
  client-dir:
    default: '{cwd}/../client'
output-dir: '{base-dir}'
options:
  '@typespec/http-client-python':
    emitter-output-dir: '{client-dir}/python'
    package-name: openmeter
    generation-subdir: _generated
    namespace: openmeter
    package-version: '0.0.0'
    generate-packaging-files: false
    license:
      name: Apache 2.0
linter:
  extends:
    - '@openmeter/api-spec/legacy'
