emit:
  - '@typespec/openapi3'
parameters:
  base-dir:
    default: '{cwd}'
output-dir: '{base-dir}'
options:
  '@typespec/openapi3':
    emitter-output-dir: '{output-dir}/output/definitions/metering-and-billing/v3'
    omit-unreachable-types: true
linter:
  extends:
    - '@openmeter/api-spec/aip'
