name: Node.js Client Generation

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.yaml
      - ".github/workflows/generate-client-node.yaml"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./api/client/node/package-lock.json"
      - name: Install Dependencies
        run: npm ci
        working-directory: ./api/client/node
      - name: Generate Client
        run: npm run generate
        working-directory: ./api/client/node
      - name: Bump Version
        run: |
          npm version prerelease --preid=beta -m "chore(api): bump Node.js client version to %s"
        working-directory: ./api/client/node
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: openapi/node-client
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate node client"
          title: "[bot] Re-generate Node.js client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ steps.app-token.outputs.token }}
